"""
Batch video captioning using cosmos-reason2-inference online mode.

Usage (shard file, recommended for distributed runs):
    python batch_caption.py --video-list shards/shard_00.txt --output-dir /out --port 8000
    python batch_caption.py --video-list shards/shard_01.txt --output-dir /out --port 8001

Usage (single machine, all videos):
    python batch_caption.py --output-dir /out --skip-existing
"""

import argparse
import subprocess
import sys
from pathlib import Path


SEPARATOR = "-" * 20


def extract_assistant_content(output: str) -> str:
    lines = output.splitlines()
    capturing = False
    result_lines = []
    for line in lines:
        if line.strip() == SEPARATOR:
            if capturing:
                break
            continue
        if line.strip() == "Assistant:":
            capturing = True
            continue
        if capturing:
            result_lines.append(line)
    return "\n".join(result_lines).strip()


def run_inference(video_path: Path, prompt_file: str, port: int, fps: int) -> str:
    cmd = [
        "cosmos-reason2-inference", "online",
        "--port", str(port),
        "-i", prompt_file,
        "--videos", str(video_path),
        "--fps", str(fps),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip())
    return result.stdout


def load_video_list(video_list: Path) -> list[Path]:
    lines = video_list.read_text(encoding="utf-8").splitlines()
    return [Path(line.strip()) for line in lines if line.strip()]


def process_videos(
    video_files: list[Path],
    output_dir: Path,
    prompt_file: str,
    port: int,
    fps: int,
    skip_existing: bool,
):
    output_dir.mkdir(parents=True, exist_ok=True)
    total = len(video_files)
    skipped = 0
    success = 0
    failed = 0

    for idx, video_path in enumerate(video_files, 1):
        output_path = output_dir / (video_path.stem + ".txt")
        print(f"[{idx}/{total}] {video_path.name}")

        if skip_existing and output_path.exists():
            print(f"  -> Skipped (already exists)")
            skipped += 1
            continue

        try:
            raw_output = run_inference(video_path, prompt_file, port, fps)
            content = extract_assistant_content(raw_output)
            output_path.write_text(content, encoding="utf-8")
            print(f"  -> Saved: {output_path}")
            success += 1
        except RuntimeError as e:
            print(f"  -> Failed: {e}", file=sys.stderr)
            failed += 1

    print(f"\nDone. success={success}, skipped={skipped}, failed={failed}")


def main():
    parser = argparse.ArgumentParser(description="Batch video captioning with cosmos-reason2 (online)")
    source = parser.add_mutually_exclusive_group()
    source.add_argument(
        "--video-list",
        type=Path,
        help="Text file with one video path per line (generated by generate_shards.py)",
    )
    source.add_argument(
        "--input-dir",
        type=Path,
        default=Path("/Data1/home/bskang/cds-data/front_camera_videos"),
        help="Directory containing input .mp4 files (used when --video-list is not given)",
    )
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--prompt-file", default="prompts/caption_detail.yaml")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--fps", type=int, default=4)
    parser.add_argument(
        "--skip-existing",
        action="store_true",
        help="Skip videos whose output .txt already exists (safe restart after failure)",
    )
    args = parser.parse_args()

    if args.video_list:
        video_files = load_video_list(args.video_list)
        print(f"Loaded {len(video_files)} videos from {args.video_list}")
    else:
        video_files = sorted(args.input_dir.glob("*.mp4"))
        if not video_files:
            print(f"No .mp4 files found in {args.input_dir}")
            return
        print(f"Found {len(video_files)} videos in {args.input_dir}")

    process_videos(
        video_files=video_files,
        output_dir=args.output_dir,
        prompt_file=args.prompt_file,
        port=args.port,
        fps=args.fps,
        skip_existing=args.skip_existing,
    )


if __name__ == "__main__":
    main()
